### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by enderphan94** [microsoft/verisol#223]
I got this error in MacOS

```
$VeriSol ERC1155ERC721.sol ERC1155ERC721
... Downloading z3.zip from https://github.com/Z3Prover/z3/releases/download/z3-4.8.4/z3-4.8.4.d6df51951f4c-x64-osx-10.14.1.zip to /Users/macbookpro/.dotnet/tools/Temp/

Unhandled Exception: System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at VeriSolRunner.ExternalTools.DownloadedToolManager.RunCmd(String cmdName, String arguments) in c:\verisol\sources\ExternalToolsManager\DownloadedToolManager.cs:line 105
   at VeriSolRunner.ExternalTools.DownloadedToolManager.ChangePermission() in c:\verisol\sources\ExternalToolsManager\DownloadedToolManager.cs:line 91
   at VeriSolRunner.ExternalTools.DownloadedToolManager.EnsureExisted() in c:\verisol\sources\ExternalToolsManager\DownloadedToolManager.cs:line 79
   at VeriSolRunner.ExternalTools.ExternalToolsManager.EnsureAllExisted() in c:\verisol\sources\ExternalToolsManager\ExternalToolsManager.cs:line 51
   at VeriSolRunner.Program.Main(String[] args) in c:\verisol\sources\VeriSol\Program.cs:line 27
zsh: abort      VeriSol ERC1155ERC721.sol ERC1155ERC721
```

**Comment by shuvendu-lahiri** [comment]
@XinxingLiu  @garbervetsky  can either of you repro the issue?

@enderphan94 did you follow instructions to first install the solc for mac?

**Comment by enderphan94** [comment]
@shuvendu-lahiri  Yes, I did

**Comment by garbervetsky** [comment]
@shuvendu-lahiri I need to do the repro. I don't  recall exactly but I remember that I needed to manually copy z3 to binaries or .net tool folder.  As soon as I get a PC I can try to repro.
