### ISSUE TITLE
Unhandled Exception : System.IO.IOException: Broken pipe

### ISSUE THREAD

**Issue by fog93** [microsoft/verisol#246]
Verification will not proceed with the following errors. in mac Os.
What's the problem?
```
Unhandled Exception: System.IO.IOException: Broken pipe
   at System.IO.FileStream.WriteNative(ReadOnlySpan`1 source)
   at System.IO.FileStream.FlushWriteBuffer()
   at System.IO.FileStream.Flush(Boolean flushToDisk)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at SolidityAST.SolidityCompiler.RunSolc(String solcPath, String derivedFilePath) in /usr/local/Cellar/solidity/0.5.11/bin/verisol/Sources/SolidityAST/SolidityCompiler.cs:line 69
   at SolidityAST.SolidityCompiler.Compile(String solcPath, String derivedFilePath) in /usr/local/Cellar/solidity/0.5.11/bin/verisol/Sources/SolidityAST/SolidityCompiler.cs:line 24
   at VeriSolRunner.VeriSolExecutor.ExecuteSolToBoogie() in /usr/local/Cellar/solidity/0.5.11/bin/verisol/Sources/VeriSol/VeriSolExecuter.cs:line 359
   at VeriSolRunner.VeriSolExecutor.Execute() in /usr/local/Cellar/solidity/0.5.11/bin/verisol/Sources/VeriSol/VeriSolExecuter.cs:line 63
   at VeriSolRunner.Program.Main(String[] args) in /usr/local/Cellar/solidity/0.5.11/bin/verisol/Sources/VeriSol/Program.cs:line 58
Abort trap: 6
```

**Comment by shuvendu-lahiri** [comment]
Can you please check if your path has any spaces?
