### ISSUE TITLE
Common ArgumentNullException

### ISSUE THREAD

**Issue by rongpan** [Microsoft/verisol#46]
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

Happens in:
file: ProcedureTranslator.cs
method: CreateDistinctArrayMappingAddress()
line: functionToLocalVarsMap[currentFunction].Add(tmpVar);

Example:
Test/regressions/LoopContinue.sol

**Comment by rongpan** [comment]
duplicated
#30
